[build]
  publish = "dist"
  command = "gridsome build"

[[redirects]]
  from = "/posts/2018/*"
  to = "/posts/:slug"
  status = 301

[[redirects]]
  from = "/posts/2017/*"
  to = "/posts/:slug"
  status = 301

[[redirects]]
  from = "/posts/2016/*"
  to = "/posts/:slug"
  status = 301

[[redirects]]
  from = "/posts/2018/just-stop"
  to = "/posts"
  status = 301